version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 5002:2345
    volumes:
      - .:/timezone_web
    env_file: .env
    container_name: go-timezone
    security_opt:
      - seccomp:unconfined
    depends_on:
      database:
        condition: service_healthy

  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_HOST: "%"
    container_name: timezone-db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 33068:3306
    volumes:
      - timezone_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: "1s"
      timeout: "10s"
      retries: 10
      start_period: "1s"

  adminer:
    image: adminer
    ports:
      - 5001:8080

volumes:
  timezone_db:
